apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: mc61l0688-python
  janus-idp.io/tekton: mc61l0688-python
  backstage.io/kubernetes-id: mc61l0688-python
  backstage.io/kubernetes-namespace: tssc-app 
  app.kubernetes.io/part-of: mc61l0688-python
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
